language: node_js
node_js:
  - "stable"
sudo: true
dist: trusty

branches:
  only:
  - master
  - feature/travis-ci

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run test:unit
  - npm run test:e2e
  - npm run build