language: node_js
node_js:
  - 10
sudo: true
dist: trusty

branches:
  only:
  - master
  - develop
  - /^feature/.*$/
  - /^hotfix/.*$/
  - /^release/.*$/

cache:
  directories:
    - node_modules

install:
  - npm install

after_failure:
  - cat /home/travis/.npm/_logs/*-debug.log

jobs:
  include:
    - stage: test

      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable

      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start

      script:
        - npm run lint
        - npm run test:unit
        - npm run test:e2e
        - npm run build

    - stage: deploy
      if: branch = master
      script:
        - chmod +x ./scripts/publish.sh
        - ./scripts/publish.sh

    - stage: audit
      script:
        - chmod +x ./scripts/audit.sh
        - ./scripts/audit.sh