language: node_js
node_js:
  - "stable"
sudo: true
dist: trusty

branches:
  only:
  - master
  - feature/travis-ci

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install netlify-cli -g

install:
  - npm install

jobs:
  include:
    - stage: test
      script:
        - npm run lint
        - npm run test:unit
        - npm run test:e2e
        - npm run build

    - stage: deploy
      if: branch = master
      script:
        - chmod +x ./scripts/publish.sh
        - ./scripts/publish.sh

    - stage: audit
      script:
        - chmod +x ./scripts/audit.sh
        - ./scripts/audit.sh