language: node_js
node_js:
  - "stable"
sudo: true
dist: trusty

branches:
  only:
  - master
  - feature/travis-ci

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

jobs:
  include:
    - stage: test
      script: npm run lint
    - script: npm run test:unit
    - script: npm run test:e2e

    - stage: build
      script: npm run build

    - stage: audit
      if: type = api
      script: